version: '3.8'

services:

  nginx:
    image: nginx:1.23.4
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api

  api:
    build: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 80
    volumes:
      - ./backend:/usr/src/app
      - ./data_base:/usr/src/data_base
    expose:
      - "80"
    depends_on:
      - db

  db:
    image: postgres:13.4
    expose:
      - 5432
    env_file:
      - ./backend/.env
