"""fix

Revision ID: 8727a5173ecc
Revises: 410813e1db2d
Create Date: 2023-05-19 10:20:10.108705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8727a5173ecc'
down_revision = '410813e1db2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
