"""remake user model

Revision ID: 90935222af8f
Revises: 8727a5173ecc
Create Date: 2023-05-21 07:52:18.925180

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "90935222af8f"
down_revision = "8727a5173ecc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("password", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_constraint("user_name_key", "user", type_="unique")
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("user_name_key", "user", ["name"])
    op.drop_column("user", "password")
    # ### end Alembic commands ###
